services:
  api:
    container_name: biabank-api
    build: ./BIABankAPI
    depends_on:
      - dotnet-newrelic-base
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/BIABankDb.db
      - Jwt__Key=${JWT_SECRET_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
      - RESEND_FROM_NAME=${RESEND_FROM_NAME}
      - AppSettings__BaseUrl=${APP_BASE_URL}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=BIABank-API
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
    volumes:
      - sqlite_data:/app/data
    restart: unless-stopped

  web:
    container_name: biabank-web
    build: ./BIABankMVC
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ApiSettings__BaseUrl=http://api:8080/
      - Jwt__Key=${JWT_SECRET_KEY}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=BIABank-MVC
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: biabank-nginx
    profiles: ["prod"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
      - api
    restart: unless-stopped

  dotnet-newrelic-base:
      build:
        context: ./docker/dotnet-newrelic-base
      image: dotnet-newrelic-base

volumes:
  sqlite_data:
